### ISSUE TITLE
hiq-python installation problem

### ISSUE THREAD

**Issue by ernop** [juncongmoo/pyllama#11]
My process
* anaconda powershell
* python 3.10
* pip install pyllama
* git clone https://github.com/juncongmoo/pyllama.git
* cd pyllama
* run inference => failure
* pip install -r requirements.txt
* get the following error
![image](https://user-images.githubusercontent.com/1008221/223811849-6077e31c-d4e4-447d-8af9-4cea18df85ca.png)

  Using cached hiq_python-1.0.0-py3-none-any.whl (49 kB)
ERROR: Cannot install hiq-python==1.0.0, hiq-python==1.0.1, hiq-python==1.0.2, hiq-python==1.0.3, hiq-python==1.0.4, hiq-python==1.0.5, hiq-python==1.1.0, hiq-python==1.1.1, hiq-python==1.1.2, hiq-python==1.1.3, hiq-python==1.1.4, hiq-python==1.1.5, hiq-python==1.1.6, hiq-python==1.1.7 and hiq-python==1.1.8 because these package versions have conflicting dependencies.

The conflict is caused by:
    hiq-python 1.1.8 depends on py-itree
    hiq-python 1.1.7 depends on py-itree
    hiq-python 1.1.6 depends on py-itree
    hiq-python 1.1.5 depends on py-itree
    hiq-python 1.1.4 depends on py-itree
    hiq-python 1.1.3 depends on py-itree
    hiq-python 1.1.2 depends on py-itree
    hiq-python 1.1.1 depends on py-itree~=0.0.15
    hiq-python 1.1.0 depends on py-itree~=0.0.15
    hiq-python 1.0.5 depends on py-itree~=0.0.15
    hiq-python 1.0.4 depends on py-itree~=0.0.15
    hiq-python 1.0.3 depends on py-itree~=0.0.15
    hiq-python 1.0.2 depends on py-itree~=0.0.14
    hiq-python 1.0.1 depends on py-itree~=0.0.14
    hiq-python 1.0.0 depends on py-itree~=0.0.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Things I've tried
* there are no listed version requirements in requirement.txt to loosen
* uninstall, reinstall pyllama, hiq
* uninstall, reinstall torch
* `pip install py-itree` => "ERROR: No matching distribution found for py-itree"

My thought now is that it's because python 3.10 is too far in the future?

Next steps: recreate environment with python 3.8, which I've seen referenced around, and try again.

**Comment by ernop** [comment]
Update:
* new conda environment with python3.8
* pip install -r requirements.txt
* failure again

```(py38) PS D:\proj\llama\pyllama> pip install -r .\requirements.txt
Collecting torch
  Downloading torch-1.13.1-cp38-cp38-win_amd64.whl (162.6 MB)
     ---------------------------------------- 162.6/162.6 MB 1.9 MB/s eta 0:00:00
Collecting fairscale
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fire
  Using cached fire-0.5.0.tar.gz (88 kB)
  Preparing metadata (setup.py) ... done
Collecting hiq-python
  Using cached hiq_python-1.1.8-py3-none-any.whl (148 kB)
Collecting sentencepiece
  Downloading sentencepiece-0.1.97-cp38-cp38-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 3.4 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement py-itree (from versions: none)
ERROR: No matching distribution found for py-itree```

step 2
* then do pip install pyllama
* this succeeds
* python inference.py <params>
* error: ModuleNotFoundError: No module named 'hiq'
* pip install hiq => succeeds "Successfully installed hiq-0.0.1" [but this may not be the right hiq?]
* python inference.py => same problem ModuleNotFoundError: No module named 'hiq'"
* pip uninstall hiq
* pip install hiq-python
* same error as above: ERROR: Cannot install hiq-python==1.0.0, hiq-python==1.0.1, hiq-python==1.0.2, hiq-python==1.0.3, hiq-python==1.0.4, hiq-python==1.0.5, hiq-python==1.1.0, hiq-python==1.1.1, hiq-python==1.1.2, hiq-python==1.1.3, hiq-python==1.1.4, hiq-python==1.1.5, hiq-python==1.1.6, hiq-python==1.1.7 and hiq-python==1.1.8 because these package versions have conflicting dependencies.

**Comment by juncongmoo** [comment]
Please use `pip install py-itree==0.0.17` to install it for windows.

**Comment by liushaowei123** [comment]
import _itree
ModuleNotFoundError: No module named '_itree'

**Comment by liushaowei123** [comment]
Use    py-itree      0.0.17
Meet error
AttributeError: module 'itree' has no attribute 'Node'

**Comment by juncongmoo** [comment]
> Use py-itree 0.0.17 Meet error AttributeError: module 'itree' has no attribute 'Node'

Can you please post your screenshot of you error? It works well for me as below:
```
>>> import itree
>>> itree.Node
<class 'itree.node.Node'>
>>> itree.__version__
'0.0.17'
```

**Comment by lingluo-maple** [comment]
> Use py-itree 0.0.17 Meet error AttributeError: module 'itree' has no attribute 'Node'

same error, I find it is beacuse I have already installed itree (not py-itree)
after uninstall itree, I get a new error:

```
>>> import itree
Traceback (most recent call last):
  File "C:\...\Python39\lib\site-packages\itree\__init__.py", line 5, in <module>
    from . import _itree
ImportError: DLL load failed while importing _itree

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\Python39\lib\site-packages\itree\__init__.py", line 7, in <module>
    import _itree
ModuleNotFoundError: No module named '_itree'
```

**Comment by bansan85** [comment]
Maybe same problem #8

**Comment by juncongmoo** [comment]
It should work now with the latest version: https://github.com/juncongmoo/itree#installation
