### ISSUE TITLE
Sorry,I can't run

### ISSUE THREAD

**Issue by KingingWang** [juncongmoo/pyllama#12]
(llama) -bash-4.2$ python inference.py --ckpt_dir ./models/7B --tokenizer_path ./models/tokenizer.model
Traceback (most recent call last):
  File "/home/ycshu_wlxy/kingingwang/pyllama-main/inference.py", line 67, in <module>
    run(
  File "/home/ycshu_wlxy/kingingwang/pyllama-main/inference.py", line 47, in run
    generator = load(ckpt_dir, tokenizer_path, local_rank, world_size, max_seq_len, max_batch_size)
  File "/home/ycshu_wlxy/kingingwang/pyllama-main/inference.py", line 22, in load
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/home/ycshu_wlxy/.conda/envs/llama/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ycshu_wlxy/.conda/envs/llama/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ycshu_wlxy/.conda/envs/llama/lib/python3.10/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ycshu_wlxy/.conda/envs/llama/lib/python3.10/site-packages/torch/serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: PytorchStreamReader failed reading file data/22: invalid header or archive is corrupted

**Comment by vo2021** [comment]
`invalid header or archive is corrupted` model file is corrupted

**Comment by KingingWang** [comment]
I prepare to re-download the pth file





------------------ Original ------------------
From: Juncong Moo ***@***.***&gt;
Date: Thu,Mar 9,2023 4:52 PM
To: juncongmoo/pyllama ***@***.***&gt;
Cc: KingingWang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [juncongmoo/pyllama] Sorry,I can't run (Issue #12)





 
Are your model files valid?

**Comment by KingingWang** [comment]
thanks,but when I use `python web_server_single.py --ckpt_dir ../../models/7B --tokenizer_path ../../models/tokenizer.model`
I see 
``` shell
(llama) -bash-4.2$ python web_server_single.py --ckpt_dir ../../models/7B --tokenizer_path ../../models/tokenizer.model
INFO:     Started server process [34473]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     12.12.12.202:51248 - "GET / HTTP/1.1" 404 Not Found
INFO:     12.12.12.202:51248 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     12.12.12.202:51248 - "GET / HTTP/1.1" 404 Not Found
```

**Comment by shadowwalker2718** [comment]
I guess absolute URI is required?

**Comment by SWHL** [comment]
> same problem and I dont konw why it returns 404

you can try https://github.com/SWHL/LLaMADemo
