### ISSUE TITLE
ModuleNotFoundError: No module named 'quant_cuda'

### ISSUE THREAD

**Issue by WeissAzura** [juncongmoo/pyllama#30]
I got this error when running " !python3 -m llama.llama_quant --help " on Google Colab

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/llama/llama_quant.py", line 6, in <module>
    from gptq import (
  File "/usr/local/lib/python3.9/dist-packages/gptq/__init__.py", line 9, in <module>
    from .gptq import GPTQ
  File "/usr/local/lib/python3.9/dist-packages/gptq/gptq.py", line 5, in <module>
    from .quant import quantize
  File "/usr/local/lib/python3.9/dist-packages/gptq/quant.py", line 4, in <module>
    from quant_cuda import matvmul2, matvmul3, matvmul4, matvmul8, matvmul16
ModuleNotFoundError: No module named 'quant_cuda'

**Comment by juncongmoo** [comment]
Can you reinstall `gptq` and make sure the local compilation is successful?

URL: https://pypi.org/project/gptq/

**Comment by WeissAzura** [comment]
It's fixed now, thanks
