### ISSUE TITLE
"KeyError: 'llama'"

### ISSUE THREAD

**Issue by DirtyKnightForVi** [juncongmoo/pyllama#39]
When debugging the code for the quota section, I received an error message saying "KeyError: 'llama'", and upgrading the transformer did not work.
```
    dataloader, testloader = get_loaders(
        args.dataset, # C4
        nsamples=args.nsamples,
        seed=args.seed,
        # model=args.model,
        model='D:\\SPACE_Research_AI\\QutaModel_TransformerBased\\modelCk\\models--decapoda-research--llama-7b-hf\\'
              'snapshots\\5f98eefcc80e437ef68d457ad7bf167c2c6a1348',
        seqlen=model.seqlen,
    )
```

**Comment by DirtyKnightForVi** [comment]
When I downloaded the complete model, I encountered an error while loading the Tokenizer.
`Traceback (most recent call last):
  File "D:\SPACE_Research_AI\QutaModel_TransformerBased\Model_quta.py", line 505, in <module>
    run()
  File "D:\SPACE_Research_AI\QutaModel_TransformerBased\Model_quta.py", line 460, in run
    dataloader, testloader = get_loaders(
  File "D:\Python\Python3_10_8\lib\site-packages\gptq\datautils.py", line 112, in get_loaders
    return get_c4(nsamples, seed, seqlen, model, tokenizer)
  File "D:\Python\Python3_10_8\lib\site-packages\gptq\datautils.py", line 67, in get_c4
    tokenizer = tokenizer or AutoTokenizer.from_pretrained(model, use_fast=False)
  File "D:\Python\Python3_10_8\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LlaMATokenizer does not exist or is not currently imported.`
