### ISSUE TITLE
run inference.py and it  report 'model parallel group is not initialized' error

### ISSUE THREAD

**Issue by MewemeW** [juncongmoo/pyllama#4]
I have set torch.distributed.init_process_group and it still got this error:

```
Traceback (most recent call last):
  File "inference.py", line 67, in <module>
    run(
  File "inference.py", line 48, in run
    generator = load(ckpt_dir, tokenizer_path, local_rank, world_size, max_seq_len, max_batch_size)
  File "inference.py", line 32, in load
    model = Transformer(model_args)
  File "/usr/local/lib/python3.8/dist-packages/llama/model.py", line 205, in __init__
    self.tok_embeddings = ParallelEmbedding(
  File "/usr/local/lib/python3.8/dist-packages/fairscale/nn/model_parallel/layers.py", line 186, in __init__
    world_size = get_model_parallel_world_size()
  File "/usr/local/lib/python3.8/dist-packages/fairscale/nn/model_parallel/initialize.py", line 152, in get_model_parallel_world_size
    return torch.distributed.get_world_size(group=get_model_parallel_group())
  File "/usr/local/lib/python3.8/dist-packages/fairscale/nn/model_parallel/initialize.py", line 128, in get_model_parallel_group
    assert _MODEL_PARALLEL_GROUP is not None, "model parallel group is not initialized"
AssertionError: model parallel group is not initialized
```
how to solve this? many thx.

**Comment by juncongmoo** [comment]
Please uninstall the original `llama` module and use `pip install pyllama`
