### ISSUE TITLE
pyllama/downloads returns empty folders

### ISSUE THREAD

**Issue by flyjgh** [juncongmoo/pyllama#47]
Hello, when running:
```
python3 -m llama.download
```
the command runs almost instantly but only creates empty folders named `7B`, `13B`, etc...
I also tried by specifying `--model-size` and `--folder` with the same result

**Comment by juncongmoo** [comment]
Just updated the code base. Can you reinstall pyllama and try?

**Comment by lucascr91** [comment]
Same problem in Mac M1

**Comment by ivanstepanovftw** [comment]
Same in Fedora

**Comment by lesurJ** [comment]
same problem for me here (intel mac)

**Comment by shadowwalker2718** [comment]
Do you have `wget` installed? You need to install `wget` otherwise you will only get empty folder.

**Comment by lucascr91** [comment]
I have wget installed and in my path. It doesn't work

**Comment by juncongmoo** [comment]
I can not reproduce the error. It always work for me.

![image](https://user-images.githubusercontent.com/94136485/227412766-18fbfad4-8dc6-446b-82e2-2deb1ee48b7e.png)

**Comment by juncongmoo** [comment]
I think I know the reason. Will fix it soon.

**Comment by juncongmoo** [comment]
Try `pip install hiq-python -U` ?

**Comment by lesurJ** [comment]
i tried after installing wget and hiq-python but it still does not work

I do not get any warnings..

`❯ python3 -m llama.download --model_size 7B
❤️ Resume download is supported. You can ctrl-c and rerun the program to resume the downloading
Downloading tokenizer...
✅ pyllama_data/tokenizer.model
✅ pyllama_data/tokenizer_checklist.chk
Downloading 7B
✅ pyllama_data/7B/params.json
✅ pyllama_data/7B/checklist.chk
Checking checksums`

**Comment by sharlec** [comment]
same on ubuntu, I can only get the token but not the model

**Comment by mldevorg** [comment]
> same on ubuntu, I can only get the token but not the model

I am using ubuntu and it works well for me though.

**Comment by sharlec** [comment]
> same on ubuntu, I can only get the token but not the model

I was cloning the whole thing to the local folder and use the download file to download, which gives me only tokenization. Then I tried to remove everything, install pyllam from pip in a new conda environment, it is working fine now.

**Comment by alexch33** [comment]
work well on ubuntu, i pull last code from repo and reinstall pylama (pip install pyllama -U)

**Comment by llimllib** [comment]
wget is on my path, and `hiq-python` is up to date. m1 mac:

```
$ python -m llama.download --model_size 7B --folder llama
❤️ Resume download is supported. You can ctrl-c and rerun the program to resume the downloading
Downloading tokenizer...
✅ llama/tokenizer.model
✅ llama/tokenizer_checklist.chk
Downloading 7B
✅ llama/7B/params.json
✅ llama/7B/checklist.chk
Checking checksums

$ ls llama/
7B/

$ du -sh llama/
  0B	llama/
```

**Comment by michael-erasmus** [comment]
Can confirm what @llimllib said. I had to do:

```sh
pip uninstall pyllama
git clone https://github.com/juncongmoo/pyllama
pip install -e pyllama
```

After that it works for me.

I also had another issue with py_itree, as reported [here](https://github.com/juncongmoo/pyllama/issues/54). 

This was fixed by uninstalling py_itree first, then installing it from source:

```
pip uninstall py_itree
pip install https://github.com/juncongmoo/itree/archive/refs/tags/v0.0.18.tar.gz
```

**Comment by anentropic** [comment]
If you are on macos there is a problem with the `download_community.sh` script that is called from `download.py`:

- it uses `declare -A` which needs bash v4+, but macos only comes with bash 3.x
- default shell on macos is `zsh` so we can install a newer bash without breaking things, just `brew install bash`
- but the `download_community.sh` script has `#!/bin/bash` at the top which points to the system bash instead of homebrew bash (which has been installed as the default, if I `bash --version` I get `version 5.2.15` now, but in a different location)
  - we can fix this by changing the line at the top of `download_community.sh` to `#!/usr/bin/env bash`
- now we just need to `brew install wget`

After these steps I am now in the process of downloading the 7B checkpoints 🎉

**Comment by llimllib** [comment]
Hopefully this is fixed following #70 and #71, let me know if you see any problems with the updated script!

**Comment by george-adams1** [comment]
@llimllib I'm getting the same issue on windows

**Comment by AstroWa3l** [comment]
macOS running/Apple Silicon M1 empty folder always persists no matter what steps are listed here or in the linked commits.

**Comment by Genie-Liu** [comment]
Still encounter this problem after upgrading bash to v5.

**Comment by llimllib** [comment]
@Genie-Liu  @AstroWa3l  if you clone this repository and run `llama/download_community.sh 7B /tmp/llama-models` hopefully you'll get the 7B model in `/tmp/models`. Looks like there hasn't been a new release yet, so this issue will persist at least until then

**Comment by AstroWa3l** [comment]
@llimllib Unfortunately it did not fix the issue

**Comment by llimllib** [comment]
@AstroWa3l can you elaborate? Were there errors? What was the output?

**Comment by llimllib** [comment]
@anentropic I do that with all my scripts, but I've never worked on this project before and wasn't sure how they were calling the script so I didn't add it

**Comment by AstroWa3l** [comment]
@llimllib I found one error and it was due to a missing package md5sum package so I installed it and now it is downloading. But I followed your instructions and cloned the repo then ran the command you suggested to download it and it is working. I guess I was just not able to download it due to a lack of the md5sum command to check hashes. Thank you!!!

**Comment by Divjyot** [comment]
> 

✅ 

On Mac (2012) OS Catalina x64_86 architecture Intel chip.  
This works for me. I tested by running `llama/download_community.sh 7B /tmp/llama-models` , 

🔴 
However using `python3 -m llama.download --model_size 7B --folder llama/` command it fails with *recursion* error.

```
% pipenv run python3 -m llama.download --model_size 7B --folder llama/
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/my_user/pyllama/llama/download.py", line 87, in <module>
    download(args)
  File "/Users/my_user/pyllama/llama/download.py", line 20, in download
    download(args)
  File "/Users/my_user/pyllama/llama/download.py", line 20, in download
    download(args)
  File "/Users/my_user/pyllama/llama/download.py", line 20, in download
    download(args)
  [Previous line repeated 985 more times]
  File "/Users/my_user/pyllama/llama/download.py", line 17, in download
    retcode = hiq.execute_cmd(cmd, verbose=False, shell=True, runtime_output=True, env=os.environ)
  File "/Users/my_user/.local/share/virtualenvs/my-env-cIchWPfI/lib/python3.9/site-packages/hiq/utils.py", line 101, in execute_cmd
    proc = subprocess.Popen(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1737, in _execute_child
    for k, v in env.items():
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 851, in __iter__
    for key in self._mapping:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py", line 701, in __iter__
    yield self.decodekey(key)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py", line 759, in decode
    return value.decode(encoding, 'surrogateescape')
RecursionError: maximum recursion depth exceeded while calling a Python object`
```

**Comment by HaxyHaxyxy** [comment]
The real cause of the issue is that md5sum in download_community is not supported on Apple silicon.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/128981692/232334341-475970ba-6c34-434b-9272-833e56a5effa.png">

**Comment by anentropic** [comment]
Ah!  I already had this via `brew install coreutils`

**Comment by CefBoud** [comment]
Script failed on `verify` function because `md5sum` was not available on my mac m1. `brew install md5sha1sum`

**Comment by Huasito-Appel** [comment]
@mldevorg Can you tell me all the step that you make so that i can try and reproduced it, it dosent work for me on ubuntu

**Comment by GreysTone** [comment]
I tried the approach from @CefBoud on my Macbook Air M2(24G), it can solve the downloading loop mentioned above

**Comment by yufanghui** [comment]
> Can confirm what @llimllib said. I had to do:
> 
> ```shell
> pip uninstall pyllama
> git clone https://github.com/juncongmoo/pyllama
> pip install -e pyllama
> ```
> 
> After that it works for me.
> 
> I also had another issue with py_itree, as reported [here](https://github.com/juncongmoo/pyllama/issues/54). I think this is happening on Mac M1 machines.
> 
> This was fixed by uninstalling py_itree first, then installing it from source:
> 
> ```
> pip uninstall py_itree
> pip install https://github.com/juncongmoo/itree/archive/refs/tags/v0.0.18.tar.gz
> ```

work for me ,thanks👍
