### ISSUE TITLE
error when running model for inference: ModuleNotFoundError: No module named 'transformers.models.llama'

### ISSUE THREAD

**Issue by AbFynd** [juncongmoo/pyllama#48]
Hi,

   I am trying to run inference using pyllama using the quantized 4bit model on Google colab, however I get below error, after model is successfully loaded:

(The command to run inference is:
!python pyllama/quant_infer.py --wbits 4 --load drive/MyDrive/pyllama/llama-7b-4bit.pt --text "the general theory of relativity states that" --max_length 24 --cuda cuda:0)
   
   mod,126,transformers.models.llama.tokenization_llama: ModuleNotFoundError: No module named 'transformers.models.llama'

At:
  <frozen importlib._bootstrap>(973): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(1014): _gcd_import
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap>(961): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(1014): _gcd_import
  /usr/lib/python3.8/importlib/__init__.py(127): import_module
  <string>(2): <module>
  /usr/local/lib/python3.8/dist-packages/hiq/base.py(491): _h
  /usr/local/lib/python3.8/dist-packages/hiq/base.py(426): enable_hiq
  /usr/local/lib/python3.8/dist-packages/hiq/base.py(160): __init__
  /usr/local/lib/python3.8/dist-packages/hiq/base.py(722): __init__
  pyllama/quant_infer.py(6): main
  pyllama/quant_infer.py(25): <module>

🦉 transformers.models.llama.tokenization_llama.LLaMATokenizer.encode is not traced('NoneType' object has no attribute 'LLaMATokenizer')
⌛️ Loading model from drive/MyDrive/pyllama/llama-7b-4bit.pt...
✅ Model from drive/MyDrive/pyllama/llama-7b-4bit.pt is loaded successfully.
Traceback (most recent call last):
  File "pyllama/quant_infer.py", line 25, in <module>
    main()
  File "pyllama/quant_infer.py", line 19, in main
    hiq.mod("llama.llama_infer").run(args)
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 375, in __x
    s.handle_exception(f_name, e)
  File "/usr/local/lib/python3.8/dist-packages/hiq/utils.py", line 493, in __y
    r = f(s, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 353, in handle_exception
    raise e
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 368, in __x
    result = call_decorated(
  File "/usr/local/lib/python3.8/dist-packages/hiq/hiq_utils.py", line 326, in call_decorated
    return f(*args, **kwargs)
  File "<string>", line 27, in __run_quant
  File "<string>", line 11, in __run_quant
  File "/content/pyllama/llama/llama_infer.py", line 75, in run
    tokenizer = AutoTokenizer.from_pretrained(args.model)
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 375, in __x
    s.handle_exception(f_name, e)
  File "/usr/local/lib/python3.8/dist-packages/hiq/utils.py", line 493, in __y
    r = f(s, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 353, in handle_exception
    raise e
  File "/usr/local/lib/python3.8/dist-packages/hiq/base.py", line 368, in __x
    result = call_decorated(
  File "/usr/local/lib/python3.8/dist-packages/hiq/hiq_utils.py", line 326, in call_decorated
    return f(*args, **kwargs)
  File "<string>", line 27, in __from_pretrained
  File "<string>", line 11, in __from_pretrained
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by juncongmoo** [comment]
Just updated the code base. Can you reinstall pyllama and try?

**Comment by AbFynd** [comment]
Now I get the below messages regarding tensorflow & libraries not found (along with partial completion for the text "the general theory of relativity states that"):

Downloading (…)lve/main/config.json: 100% 427/427 [00:00<00:00, 45.9kB/s]
⌛️ Loading model from drive/MyDrive/pyllama/llama-7b-4bit.pt...
✅ Model from drive/MyDrive/pyllama/llama-7b-4bit.pt is loaded successfully.
Downloading tokenizer.model: 100% 500k/500k [00:00<00:00, 11.2MB/s]
Downloading (…)cial_tokens_map.json: 100% 2.00/2.00 [00:00<00:00, 937B/s]
Downloading (…)okenizer_config.json: 100% 141/141 [00:00<00:00, 57.1kB/s]
********************************************************************************
2023-03-23 07:29:14.026210: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-23 07:29:17.947839: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-23 07:29:17.949406: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-23 07:29:17.949440: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
🦙: the general theory of relativity states that:
the speed of light is a constant
the equation that describes the
****************************** GPU/CPU/Latency Profiling ******************************
[2023-03-23 07:28:19.883789 - 07:29:20.997576]  [100.00%] 🟢_root_time(61.1138)
                                                            [OH:2198044us]
[2023-03-23 07:28:19.883789 - 07:29:20.997576]  [100.00%]    l___run_quant(61.1138)
[2023-03-23 07:28:20.520134 - 07:29:05.869730]  [ 74.21%]       |___load_quant(45.3496)
[2023-03-23 07:29:07.121487 - 07:29:08.203737]  [  1.77%]       |___from_pretrained(1.0822)
[2023-03-23 07:29:08.308854 - 07:29:08.413032]  [  0.17%]       |___encode(0.1042)
[2023-03-23 07:29:08.521664 - 07:29:13.879208]  [  8.77%]       l___generate(5.3575)

[ 0.000 - 4729.000]  [100.00%] 🟢_root_total_gpu_memory_mb_nvidia_smi(4729.0000)
[ 0.000 - 4729.000]  [100.00%]    l___run_quant(4729.0000)
[ 0.000 - 823.000]  [ 17.40%]       |___load_quant(823.0000)
[4481.000 - 4729.000]  [  5.24%]       l___generate(248.0000)

[      336.824 -      4280.258]  [100.00%] 🟢_root_get_memory_mb(3943.4336)
[      336.824 -      4280.258]  [100.00%]    l___run_quant(3943.4336)
[      336.832 -      6379.230]  [153.23%]       |___load_quant(6042.3984)
[     3815.062 -      3816.145]  [  0.03%]       |___from_pretrained(1.0820)
[     3816.145 -      3816.148]  [  0.00%]       |___encode(0.0039)
[     3816.148 -      3999.309]  [  4.64%]       l___generate(183.1602)
