### ISSUE TITLE
No module named 'hiq'

### ISSUE THREAD

**Issue by zhuxiujia** [juncongmoo/pyllama#5]
G:\ai\pyllama>python inference.py --ckpt_dir G:\model\7B --tokenizer_path G:\model/tokenizer.model
Traceback (most recent call last):
  File "G:\ai\pyllama\inference.py", line 6, in <module>
    from llama import ModelArgs, Transformer, Tokenizer, LLaMA
  File "G:\ai\pyllama\llama\__init__.py", line 5, in <module>
    from .model_single import ModelArgs, Transformer
  File "G:\ai\pyllama\llama\model_single.py", line 8, in <module>
    import hiq
ModuleNotFoundError: No module named 'hiq'

**Comment by juncongmoo** [comment]
```
pip install hiq-python
```

**Comment by FarisHijazi** [comment]
please put this in the requirements.txt, I spent a few hours with this issue and was running `pip install hiq` when it should've been `pip install hiq-python`
