### ISSUE TITLE
is py-itree available for Windows?

### ISSUE THREAD

**Issue by vmajor** [juncongmoo/pyllama#8]
hiq-ptyhon depends on py-itree, but py-itree does not appear to have a windows compatible release.

**Comment by ernop** [comment]
I think the internal problem is that py-itree is not available by default on windows.

https://github.com/juncongmoo/itree

Haven't tried hard but this is where I ended up.

**Comment by vo2021** [comment]
I think you have to use Mac or Linux.

**Comment by juncongmoo** [comment]
Please use `pip install py-itree==0.0.17` to install it for windows.

**Comment by bansan85** [comment]
I just tried:

```
  File "...\pyllama-main\inference.py", line 5, in <module>
    from llama import ModelArgs, Transformer, Tokenizer, LLaMA
  File "...\pyllama-main\llama\__init__.py", line 5, in <module>
    from .model_single import ModelArgs, Transformer
  File "...\pyllama-main\llama\model_single.py", line 8, in <module>
    import hiq
  File "...\Python\Python310\lib\site-packages\hiq\__init__.py", line 57, in <module>
    from .tree import (
  File "...\Python\Python310\lib\site-packages\hiq\tree.py", line 10, in <module>
    from hiq import tree_func
  File "...\Python\Python310\lib\site-packages\hiq\tree_func.py", line 19, in <module>
    from hiq.node_utils import _c, _d
  File "...\Python\Python310\lib\site-packages\hiq\node_utils.py", line 11, in <module>
    from hiq.node import Node
  File "...\Python\Python310\lib\site-packages\hiq\node.py", line 17, in <module>
    Node = itree.Node
AttributeError: module 'itree' has no attribute 'Node'```

**Comment by Eugene-Bond** [comment]
```
Traceback (most recent call last):
  File "/Users/eugene/Work/ai/pyllama/LLaMADemo/webapp_single.py", line 7, in <module>
    from llama import ModelArgs, Transformer, Tokenizer, LLaMA
  File "/Users/eugene/Work/ai/pyllama/LLaMADemo/llama/__init__.py", line 5, in <module>
    from .model_single import ModelArgs, Transformer
  File "/Users/eugene/Work/ai/pyllama/LLaMADemo/llama/model_single.py", line 8, in <module>
    import hiq
  File "/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/hiq/__init__.py", line 57, in <module>
    from .tree import (
  File "/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/hiq/tree.py", line 9, in <module>
    import itree
  File "/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/itree/__init__.py", line 7, in <module>
    import _itree
ImportError: dlopen(/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/_itree.cpython-39-darwin.so, 0x0002): tried: '/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/_itree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/_itree.cpython-39-darwin.so' (no such file), '/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/_itree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
Doesn't work with M1 Macs. Even though the package pretends to be built with arm64 architecture. Tried out with several versions of itree, and even pythons - the same problem :(

**Comment by Eugene-Bond** [comment]
Builds locally without any problems. 
`TypeError: type torch.cuda.HalfTensor not available. Torch not compiled with CUDA enabled.` is another problem and is not related to py-itree

**Comment by juncongmoo** [comment]
@Eugene-Bond @bansan85 @vmajor 
To install `itree` in windows, there is a workaround:

- install cmake
- run the following command to build it locally:

```
pip install https://github.com/juncongmoo/itree/archive/refs/tags/tag-bf9f3aada064acf3ce4db6fc58ed2e744caee0a3.tar.gz
```

I will release a better version of solution soon. Thanks.

**Comment by bansan85** [comment]
Thanks. Just tried. Install with success but I still can't run `inference.py`

```
...\pyllama-main>py -3.10 inference.py --ckpt_dir ../7B --tokenizer_path ../tokenizer.model
Traceback (most recent call last):
  File "...\Python\Python310\lib\site-packages\itree\__init__.py", line 5, in <module>
    from . import _itree
ImportError: cannot import name '_itree' from partially initialized module 'itree' (most likely due to a circular import) (...\Python\Python310\lib\site-packages\itree\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\pyllama-main\inference.py", line 5, in <module>
    from llama import ModelArgs, Transformer, Tokenizer, LLaMA
  File "...\pyllama-main\llama\__init__.py", line 5, in <module>
    from .model_single import ModelArgs, Transformer
  File "...\pyllama-main\llama\model_single.py", line 8, in <module>
    import hiq
  File "...\Python\Python310\lib\site-packages\hiq\__init__.py", line 57, in <module>
    from .tree import (
  File "...\Python\Python310\lib\site-packages\hiq\tree.py", line 9, in <module>
    import itree
  File "...\Python\Python310\lib\site-packages\itree\__init__.py", line 7, in <module>
    import _itree
ImportError: DLL load failed while importing _itree: Le module spécifié est introuvable.

```

**Comment by Eugene-Bond** [comment]
@juncongmoo thanks. as said above, building from source and installing from built wheel works. The main problem with M1 is that pyllama could run on CPU only. Even forcing `torch.set_default_device("mps")` doesn't help as complex types are not supported :-(
```
  File "/Users/eugene/Work/ai/pyllama/src/llama/model_single.py", line 42, in precompute_freqs_cis
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
  File "/Users/eugene/Work/ai/pyllama/.venv/lib/python3.9/site-packages/torch/utils/_device.py", line 63, in __torch_function__
    return func(*args, **kwargs)
TypeError: Complex types are unsupported on MPS
```
Anyway, thanks for an interesting product and responsiveness!

**Comment by levitation** [comment]
According to https://github.com/juncongmoo/itree/issues/18#issuecomment-1471425948 you can currently use Python 3.11 to use **itree** under Windows. In my Windows machine indeed, itree installs successfully under Python 3.11 and works ok.

BUT Python 3.11 is still no good solution either. **pyllama** also depends **sentencepiece** and that package does not install under Python 3.11 again.

**Comment by thistleknot** [comment]
oh dear, so what is the solution to _itree on windows?  I suppose build it on linux (which I have), but kind of unfortunate.  The documentation highlighting this might be helpful (i.e. build instructions for windows/linux with python reqs and what works)?

**Comment by daniel-kukiela** [comment]
I am getting (Python 3.10 on Windows 10):
```
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\itree\__init__.py", line 5, in <module>
    from . import _itree
ImportError: DLL load failed while importing _itree: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Temp\LLaMA_quantization\quant_infer.py", line 1, in <module>
    import hiq, time
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\hiq\__init__.py", line 57, in <module>
    from .tree import (
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\hiq\tree.py", line 9, in <module>
    import itree
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\itree\__init__.py", line 7, in <module>
    import _itree
ModuleNotFoundError: No module named '_itree'
```
https://github.com/juncongmoo/itree/issues/18 is closed even if (IMO) not fixed. I also tried installing from sources with CMake following this: https://github.com/juncongmoo/itree#build-from-source-with-cmake - still the same error.

**Comment by ashishpatel26** [comment]
### ModuleNotFoundError: No module named '_itree'

I am facing the similar error

```python
Traceback (most recent call last):
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\itree\__init__.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/itree/__init__.py)", line 5, in <module>
    from . import _itree
ImportError: DLL load failed while importing _itree: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[c:\Users\ibm26\.conda\envs\llms\lib\runpy.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/runpy.py)", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "[c:\Users\ibm26\.conda\envs\llms\lib\runpy.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/runpy.py)", line 110, in _get_module_details
    __import__(pkg_name)
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\llama\__init__.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/llama/__init__.py)", line 17, in <module>
    from .model_single import ModelArgs, Transformer
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\llama\model_single.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/llama/model_single.py)", line 7, in <module>
    import hiq
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\hiq\__init__.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/hiq/__init__.py)", line 59, in <module>
    from .tree import get_duration_from_hiq_string, get_graph_from_string, Tree
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\hiq\tree.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/hiq/tree.py)", line 9, in <module>
    import itree
  File "[c:\Users\ibm26\.conda\envs\llms\lib\site-packages\itree\__init__.py](file:///C:/Users/ibm26/.conda/envs/llms/lib/site-packages/itree/__init__.py)", line 7, in <module>
    import _itree
ModuleNotFoundError: No module named '_itree'
```

**Comment by mypicture** [comment]
I faced the same error. Is there any solution?

**Comment by OAVallejos** [comment]
Microsoft Windows [Versión 10.0.19045.3208]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Users\juana>pip install https://github.com/juncongmoo/itree/archive/refs/tags/tag-bf9f3aada064acf3ce4db6fc58ed2e744caee0a3.tar.gz
Collecting https://github.com/juncongmoo/itree/archive/refs/tags/tag-bf9f3aada064acf3ce4db6fc58ed2e744caee0a3.tar.gz
  Downloading https://github.com/juncongmoo/itree/archive/refs/tags/tag-bf9f3aada064acf3ce4db6fc58ed2e744caee0a3.tar.gz
     / 429.6 kB 1.8 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: py-itree
  Building wheel for py-itree (pyproject.toml) ... done
  Created wheel for py-itree: filename=py_itree-0.0.18.dev0-cp39-cp39-win_amd64.whl size=410042 sha256=33b04276a943d90aeeca5f4cb9e22ea5a2ba926758deca83268ec6053d967a14
  Stored in directory: c:\users\juana\appdata\local\pip\cache\wheels\69\ff\0c\c7fc7e2a808c25bcc21cc6e5c381b2ad4f20a5f1a74e0f6f61
Successfully built py-itree
Installing collected packages: py-itree
  Attempting uninstall: py-itree
    Found existing installation: py-itree 0.0.18
    Uninstalling py-itree-0.0.18:
      Successfully uninstalled py-itree-0.0.18
Successfully installed py-itree-0.0.18.dev0

C:\Users\juana>python -m llama.download
Traceback (most recent call last):
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\site-packages\llama\download.py", line 41, in <module>
    download(get_args())
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\site-packages\llama\download.py", line 16, in download
    hiq.execute_cmd(cmd, verbose=False, shell=True, runtime_output=True)
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\site-packages\hiq\utils.py", line 101, in execute_cmd
    proc = subprocess.Popen(
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\juana\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] El parámetro no es correcto

any solution? i have windows 10: IA: The error indicates that there is a problem with the parameter supplied while running a child process. This could be caused by a problem with the package called or with the way the command is being executed.
